name: Tag and Release

on:
  push:
    branches:
      - master

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          if [ -z "$latest_tag" ]; then
            echo "::set-output name=latest_tag::v0.0.0"
          else
            echo "::set-output name=latest_tag::$latest_tag"
          fi

      - name: Calculate new tag
        id: calculate-new-tag
        run: |
          latest_tag=${{ steps.get-latest-tag.outputs.latest_tag }}
          if [ "$latest_tag" == "v0.0.0" ]; then
            new_tag="v0.0.1"
          else
            IFS='.' read -r -a parts <<< "${latest_tag:1}"
            major=${parts[0]}
            minor=${parts[1]}
            patch=${parts[2]}

            if [ $patch -eq 9 ]; then
              patch=0
              minor=$((minor + 1))
            else
              patch=$((patch + 1))
            fi

            new_tag="v${major}.${minor}.${patch}"
          fi
          echo "::set-output name=new_tag::$new_tag"

      - name: Create new tag
        run: |
          new_tag=${{ steps.calculate-new-tag.outputs.new_tag }}
          git tag $new_tag
          git push origin $new_tag

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.calculate-new-tag.outputs.new_tag }}
          release_name: Release ${{ steps.calculate-new-tag.outputs.new_tag }}
          body: |
            Release notes for ${{ steps.calculate-new-tag.outputs.new_tag }}
          draft: false
          prerelease: false
